name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  get: ^4.6.6
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/home/images/icon.png
    - assets/home/images/icon-rAm.png
    - assets/home/images/icon-mobile-signal.png
    - assets/dashboard/images/audit-logs.png
    - assets/signin/images/vector.png
    - assets/signup/images/eye-slash.png
    - assets/proceed-to-pay/images/mobile-2.png
    - assets/dashboard/images/auto-group-7wtp.png
    - assets/buydata/images/images-1.png
    - assets/dashboard/images/transactions.png
    - assets/home/images/icon-TnR.png
    - assets/dashboard/images/polygon-1.png
    - assets/dashboard/images/group-35.png
    - assets/home/images/wifi.png
    - assets/signin/images/vector-fN9.png
    - assets/proceed-to-pay/images/outlined-suggested-symbol-x.png
    - assets/dashboard/images/subscriptions.png
    - assets/dashboard/images/referrals.png
    - assets/signup/images/profile-circle.png
    - assets/signin/images/vector-gaM.png
    - assets/signin/images/shadow.png
    - assets/dashboard/images/rectangle-5.png
    - assets/dashboard/images/settings.png
    - assets/proceed-to-pay/images/photo2023-04-2801-44-15mtn-3.png
    - assets/dashboard/images/payouts.png
    - assets/dashboard/images/waving-hand-sign1f44b-1.png
    - assets/home/images/frame-48096873.png
    - assets/home/images/mobile-2-wQd.png
    - assets/signin/images/vector-FVB.png
    - assets/proceed-to-pay/images/profile-circle-DWR.png
    - assets/signin/images/vector-3VT.png
    - assets/dashboard/images/polygon-2.png
    - assets/newpassword/images/eyeopen.png
    - assets/dashboard/images/frame-2.png
    - assets/dashboard/images/polygon-2-TnZ.png
    - assets/signin/images/sms.png
    - assets/dashboard/images/frame-2-aCH.png
    - assets/home/images/photo2023-04-2801-44-15mtn-3-zgZ.png
    - assets/signup/images/sms-ChP.png
    - assets/dashboard/images/group-41.png
    - assets/dashboard/images/frame-2-GdF.png
    - assets/buydata/images/mobile-2-GZF.png
    - assets/dashboard/images/group-36.png
    - assets/home/images/battery.png
    - assets/dashboard/images/frame-2-Bwf.png
    - assets/signin/images/background-simple.png
    - assets/dashboard/images/ellipse-2.png
    - assets/home/images/fundwallet-1-3.png
    - assets/signin/images/vector-zHo.png
    - assets/newpassword/images/eyeclosed.png
    - assets/proceed-to-pay/images/images-1-QvV.png
    - assets/dashboard/images/customers.png
    - assets/home/images/images-1-R6h.png
    - assets/buydata/images/photo2023-04-2801-44-15mtn-3-T3P.png
    - assets/home/images/frame-48097061.png
    - assets/home/images/fundwallet-1-3-u6H.png
    - assets/signup/images/fundwallet-1-4.png
    - assets/buydata/images/profile-circle-tgh.png
    - assets/proceed-to-pay/images/photo2023-04-2801-44-15mtn-3-Fow.png
    - assets/dashboard/images/group-34.png
    - assets/home/images/photo2023-05-0509-46-32-1.png
    - assets/proceed-to-pay/images/photo2023-05-0509-46-32-1-NJd.png
    - assets/buydata/images/photo2023-05-0509-46-32-1-MCV.png
    - assets/signin/images/vector-fgd.png
    - assets/dashboard/images/frame-2-657.png
    - assets/dashboard/images/eva-search-outline.png
    - assets/signup/images/call.png
    - assets/dashboard/images/frame-2-mV3.png
    - assets/signin/images/eye-slash-c6u.png
    - assets/buydata/images/fundwallet-1-4-yeZ.png
    - assets/signin/images/vector-Ug9.png
    - assets/proceed-to-pay/images/fundwallet-1-4-u9T.png
    - assets/newpassword/images/fundwallet-1-4-P8V.png
    - assets/signin/images/fundwallet-1-4-ZU5.png
    - assets/forgetpassword/images/fundwallet-1-4-3u3.png
    - assets/dashboard/images/balances.png
    - assets/signin/images/character.png
    - assets/signin/images/plants.png
    - assets/dashboard/images/frame-2-HHs.png
    - assets/dashboard/images/group-22.png
    - assets/forgetpasswordotp/images/fundwallet-1-4-DnH.png
    - assets/home/images/frame-48097183.png
    - assets/signup/images/sign-up-bro.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
